name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: apt
      run: apt update
    - name: apt install
      run: apt install ninja-build

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: ninja

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
